### ISSUE TITLE
Can't run examples from the command line....?

### ISSUE THREAD

**Issue by JoshuaBatty** [sketchthat/huobi-australia#17]
Im getting the following error when trying to run examples from the command line. Im pretty new to typescript, just wondering if you've seen this before and can point me in the right direction to fix it?

`An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sureyou have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.`

Thanks.

**Comment by JoshuaBatty** [comment]
Never mind, I installed node-ts and everything is working fine. Cheers!

**Comment by sketchthat** [comment]
Yes the examples are in Typescript so the easiest way to get them working is calling them with `ts-node`.

I'll get some pure Node versions online so others can test if they get stuck.
